name: tractian_flutter_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.4
  go_router: ^14.2.7
  hooks_riverpod: ^2.5.2
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  custom_lint: ^0.6.7
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13

flutter:
  uses-material-design: true
  assets:
  - assets/icon/asset.svg
  - assets/icon/bolt.svg
  - assets/icon/boltOutline.svg
  - assets/icon/component.svg
  - assets/icon/critical.svg
  - assets/icon/criticalCircle.svg
  - assets/icon/location.svg
  - assets/icon/locationMarker.svg
  - assets/icon/logo.svg
